config/routes.rb
JC::Application.routes.draw do
  devise_for :users

  get 'about' => 'pages#about'
  get 'cameo' => 'pages#cameo'
  root :to => 'pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def action
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <small>
    <!--  <a href="http://www.google.com" >cerca qui</a> -->
    <%= link_to "cerca qui", "http://www.google.com" %>
    ... by <%= link_to "Loren Fradi", "#" %>
  </small>

</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top"> <!-- per fissare il menu in alto -->
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <%= link_to "JC PROJECT", root_path, class: "brand" %>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
        <!-- .nav, .navbar-search, .navbar-form, etc -->
				<ul class="nav">
      		<li> <%= link_to "Home", root_path %></li>
					<li><%= link_to "About", about_path %></li>
          <li><%= link_to "Cameo", cameo_path %></li>
				</ul>
				<ul class="nav pull-right">
          <li> <%= link_to "Help", '#' %></li>
          <li> <%= link_to "FAQ", '#' %></li>
      		<% if user_signed_in?%>
            <li> <%= link_to "Edit Profile",  edit_user_registration_path %></li>
            <li> <%= link_to "Logout",  destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li> <%= link_to "Login",  new_user_session_path %></li>
          <% end %>
				</ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title> JC </title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

		<%= render "layouts/header" %>
		<div class="container">
			<% flash.each do |name, msg| %>
				<%content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
			<%= render "layouts/footer" %>
		</div>
	</body>
</html>

app/views/pages/about.html.erb
<h1> About Page</h1>
<p>
	<%= link_to "JC Project", "www.google.com" %>
	per sapere  
	<%= link_to "dove", "https://maps.google.com/" %>
	andare
</p>

app/views/pages/cameo.html.erb
<div class="hero-unit">

	<h1 align="center">CAMEO</h1>

	<p> </p>
	<p align="center">SHORT RESUME</p>

		<p><a href="#" class="btn btn-large btn-warning disabled">T</a></p>
		<p><a href="#" class="btn btn-large btn-danger disabled">D</a></p>

</div>

app/views/pages/home.html.erb
<% if user_signed_in?%>
	<div class="hero-unit">
  	<h1 allign= "center"> This is Your private Home page </h1>
  	<h1 allign= "center"> ON JC </h1>
	</div>
<% else %>

	<div class="hero-unit">
	  	<h1>Welcome to JC Project</h1>
	  	<p> </p>

			<p>
				<%= link_to "Sign up now!", new_user_registration_path, class: "btn btn-primary btn-large" %> 
			</p>
	</div>
<% end %>